# Generated by Django 5.2 on 2025-07-28 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualCancer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='averagevalues',
            old_name='average_infra',
            new_name='average_SEP',
        ),
        migrations.RenameField(
            model_name='averagevalues',
            old_name='average_se_dpc',
            new_name='average_clinical_guidlines',
        ),
        migrations.RenameField(
            model_name='averagevalues',
            old_name='average_treatment',
            new_name='average_infrastructure',
        ),
        migrations.AddField(
            model_name='averagevalues',
            name='average_treatment_finding_and_awareness',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
