# Generated by Django 5.2 on 2025-08-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualCancer', '0002_rename_average_infra_averagevalues_average_sep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_type', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('country_shortForm', models.CharField(max_length=10)),
                ('introduction', models.TextField()),
                ('swot_analysis', models.JSONField()),
                ('infrastructure', models.JSONField()),
                ('survival_early_detection_palliative_care', models.JSONField()),
                ('treatment_research_awareness', models.JSONField()),
                ('biomarker_utilization', models.JSONField()),
            ],
        ),
    ]
