# Generated by Django 5.2 on 2025-08-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualCancer', '0003_overviewdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overviewdetails',
            old_name='biomarker_utilization',
            new_name='at_glance',
        ),
        migrations.RemoveField(
            model_name='overviewdetails',
            name='infrastructure',
        ),
        migrations.RemoveField(
            model_name='overviewdetails',
            name='survival_early_detection_palliative_care',
        ),
        migrations.RemoveField(
            model_name='overviewdetails',
            name='treatment_research_awareness',
        ),
    ]
