# Generated by Django 5.2 on 2025-08-23 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualCancer', '0004_rename_biomarker_utilization_overviewdetails_at_glance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overviewdetails',
            old_name='at_glance',
            new_name='biomarkers',
        ),
        migrations.AddField(
            model_name='overviewdetails',
            name='cancer_screening',
            field=models.JSONField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overviewdetails',
            name='clinical_guidelines',
            field=models.JSONField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overviewdetails',
            name='infrastructure',
            field=models.JSONField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overviewdetails',
            name='reimbursement',
            field=models.JSONField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overviewdetails',
            name='survival_rates',
            field=models.JSONField(default="null"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overviewdetails',
            name='treatment_funding_awareness',
            field=models.JSONField(default="null"),
            preserve_default=False,
        ),
    ]
