# Generated by Django 5.2 on 2025-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualCancer', '0005_rename_at_glance_overviewdetails_biomarkers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('feedback_type', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
